{
 "title": "NY Green Taxi Data Monitoring",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(prediction_drift), \"timestamp\" FROM ny_green_taxi_metrics GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Num of Drift Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(num_drifted_columns), \"timestamp\" FROM ny_green_taxi_metrics GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT SUM(share_missing_values), \"timestamp\" FROM ny_green_taxi_metrics GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  }
 ]
}